######securityContext was added in record 67
#[2023-02-08T02:29:52.630Z] FAIL - k8s_deployment_service.yaml - main - Containers must not run as root - use runAsNonRoot wihin container security context
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-svc
  name: demo-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-svc
  strategy: {}
  template:
    metadata:
      labels:
        app: demo-svc
    spec:
      serviceAccountName: default
      containers:
      - image: replace
        name: demo-con
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-svc
  name: demo-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30004
  selector:
    app: demo-svc
  type: NodePort