apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-svc
  name: demo-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-svc
  strategy: {}
  template:
    metadata:
      labels:
        app: demo-svc
    spec:
      serviceAccountName: default
      volumes:
      - name: vol
        emptyDir: {}
      containers:
      - image: replace
        name: demo-con
        volumeMounts:
          - mountPath: /tmp
            name: vol
        securityContext:
          capabilities:
            drop:
             - NET_RAW
          runAsUser: 100
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        resources:
         requests:
          memory: "256Mi"
          cpu: "200m"
         limits:
          memory: "512Mi"
          cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-svc
  name: demo-svc-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: demo-svc
  type: ClusterIP