---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lab-west-prod
  name: west-prod-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30005
  selector:
    app: lab-west-prod
  type: NodePort