apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lab-west-prod
  name: west-prod-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab-west-prod
  strategy: {}
  template:
    metadata:
      labels:
        app: lab-west-prod
    spec:
      serviceAccountName: default
      volumes:
      - name: vol
        emptyDir: {}
      containers:
      - image: replace
        name: west-prod-con
        volumeMounts:
          - mountPath: /tmp
            name: vol
        securityContext:
          capabilities:
            drop:
             - NET_RAW
          runAsUser: 100
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        resources:
         requests:
          memory: "256Mi"
          cpu: "200m"
         limits:
          memory: "512Mi"
          cpu: "500m"
